config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :users do
    resources :groups do
      resources :budgets
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Budget, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :groups, dependent: :destroy

  validates :name, :amount, presence: true
end

app/models/budgets_group.rb
class BudgetsGroup < ApplicationRecord
  # belongs_to :budget
  # belongs_to :group
  belongs_to :groups, class_name: 'Group'
  belongs_to :budgets, class_name: 'Budget'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :budgets, dependent: :destroy

  validates :name, presence: true, length: { in: 3..50 }
  validates :icon, presence: true, length: { in: 10..500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :groups, foreign_key: 'user_id'
  has_many :budgets, foreign_key: 'user_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :surname, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :password, :current_password) }
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :fetch_group
  def index
    @user = current_user
    @budgets = @group.budgets
    @total = @budgets.sum(:amount)
  end

  def new
    @budget = Budget.new
  end

  def create
    @user = User.find(params[:user_id])
    @budget = Budget.new(budget_params)
    @budget.user_id = current_user.id
    if @budget.valid?
      @budget.save
      @budget.groups.push(@group)
      flash[:notice] = 'New Budget Successfully Created'
      redirect_to user_group_budgets_path
    else
      render :new
    end
  end

  def destroy
    @budget = Budget.find_by(id: params[:id])
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to user_group_budgets_path, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def budget_params
    params.require(:budget).permit(:name, :amount)
  end

  def fetch_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :fetch_group, only: %i[destroy]
  def index
    if user_signed_in?
      @user = current_user
      @groups = @user.groups.order('created_at DESC')
      @budgets = Budget.all
    else
      render root_path
    end
  end

  def new
    @user = User.find(params[:user_id])
    @group = Group.new
  end

  def create
    puts group_params
    @user = User.find(params[:user_id])
    @group = Group.new(group_params)
    @group.user_id = @user.id
    if @group.valid?
      @group.save
      flash[:notice] = 'New group Created Successfully'
      redirect_to user_groups_path
    else
      flash[:notice] = 'Input a valid Icon image and Name.'
      render :new
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path, notice: 'Group has been successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  def group_params
    params.require(:group).permit!
  end

  def fetch_group
    @group = Group.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_budget.html.erb
<div class="budget-display card mt-1 shadow p-3 mb-1 bg-body rounded w-10">
    <div class="budget-display d-flex p-1 w-8 gap-5">
      <h6>Name: <%= budget.name %></h6>
      <h6>Amount: <%= number_to_currency(budget.amount) %></h6>
      <div class="d-flex gap-4">
        <%= button_to "Delete", user_group_budget_path(current_user, @group, budget), method: :delete, class: 'btn btn-danger p-2' %>
      </div>
    </div> 
</div>

app/views/budgets/index.html.erb
<div class="container">
  <div class="budget-header">
    <h1> <%= link_to user_groups_path do %>
      <i class="fa fa-arrow-left" aria-hidden="true" style="color: #3778c2; padding-left: 22px"> </i>
      <% end %>
      </h1>
  </div>
  <h2 class="d-flex justify-content-center align-items-center budget-title">Transactions</h2>
  <% if @budgets.count > 0 %>
    <div class="card p-4">
      <div class="budget-total d-flex justify-content-between">
        <h3><%= @group.name %>:</h3>
        <h3> <%= number_to_currency(@budgets.sum(&:amount)) %> </h3>
      </div>
      <div class="card-body d-flex flex-column">      
        <% @budgets.each do |budget|%>
          <div class="d-flex ms-1 mb-3 gap-5 align-items-center justify-content-between">
            <img src="<%= @group.icon %>", width="50", height="50", alt="group_icon" class: "card-img">
            <%= render budget %>
          </div>
         
        <% end %>        
      </div>
    <% else %>
      <span class="d-flex justify-content-center align-items-center shadow p-3 mb-5 bg-body rounded p-5" >You have no Transactions click Add Transaction to continue</span>
    <% end %>
    <div class='add-group-btn'>
      <div class='group-btn shadow p-3 mb-5 rounded'>
        <%= link_to "Add Transaction", new_user_group_budget_path(current_user, @group.id), class: 'new-group-btn text-dark' %>
      </div>
    </div>
  </div>
</div>

app/views/budgets/new.html.erb
<nav class="container-fluid navbar navbar-expand-md bg-primary">
    <div class="container-fluid d-flex align-items-center justify-content-between">
    <div></div>
      <div class="nav-logo">        
        <h2><span class="bud">Add Budget</span></h2>
      </div>
      <button class="navbar-toggler btn btn-outline-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item"> 
              <span class="nav-link me-5 text-light"><i class="fa fa-user me-2"></i><%= current_user.name %></span>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-sm btn-outline-warning mt-2' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_session_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<div class="container d-flex flex-column justify-content-center align-items-center">
  <div class="budget-header w-100">
    <h1>
      <%= link_to user_group_budgets_path(current_user, @group) do %>
        <i class="fa fa-arrow-left" aria-hidden="true" style="color: #3778c2; padding-left: 22px"> </i>
      <% end %>
    </h1>
  </div>
  <div class="card w-100 d-flex justify-content-center align-items-center  p-3 shadow p-3 mb-5 bg-body rounded">
    <h2 class="budget-title">Create New Tranasction</h2>
    <%= form_with model: @budget, url: user_group_budgets_path(current_user, @group), method: :post, scope: :budget,  class: 'd-flex flex-column  col-md-5 justify-content-center align-items-center' do |f| %> 
      <br/>
      <div class="input-group p-2 mb-3">
        <%= f.label :name, class: "input-group-text" %><br />
        <%= f.text_field :name,  autofocus: true, autocomplete: "name", class: 'form-control' %>
      </div>

      <div class="input-group p-2 mb-3">
        <%= f.label :amount, class: "input-group-text" %><br />
        <%= f.number_field :amount, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Save Transaction", class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<nav class="container-fluid navbar navbar-expand-md bg-primary">
    <div class="container-fluid d-flex align-items-center justify-content-between">
    <div></div>
      <div class="nav-logo">        
        <h2><span class="bud">Transaction</span></h2>
      </div>
      <button class="navbar-toggler btn btn-outline-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item"> 
              <span class="nav-link me-5 text-light"><i class="fa fa-user me-2"></i><%= current_user.name %></span>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-sm btn-outline-warning mt-2' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_session_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<div class="container">
  <div class="total">
      <h3>Overall Budget:</h3>
      <h3> <%= number_to_currency(@budgets.sum(&:amount)) %> </h3>
  </div>
  <% if @groups.count > 0 %>
    <% @groups.each do |group|%>
      <div class="card mb-4 px-3 p-3 shadow p-3 mb-5 bg-body rounded">
        <%= link_to user_group_budgets_path(current_user, group.id), class: "text-decoration-none" do %>
          <div class="d-flex">
            <img src="<%= group.icon %>", width="100", height="100", alt="group_icon", class:'me-3 p-3 border border-white rounded-circle'>        
            <div class="card-title ms-5 d-flex justify-content-between w-100">
              <div>
                
                  <h2 class="border border-white rounded-3"> <%= group.name %></h2>
                
                <span> <%= group.created_at.strftime("%B, %e at %H:%M") %> </span>
              </div>
                <div class="d-flex flex-column justify-content-between align-items-between gap-10">
                  <span class="each-group-amount">Total Budget: $<%= group.budgets.sum(&:amount) %></span>
                  <%= button_to "Delete Group", user_group_path(current_user, group), method: :delete, class: 'btn btn-danger p-2' %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
  <% else %>
    <span class="d-flex justify-content-center align-items-center shadow p-3 mb-5 bg-body rounded p-5"> click Add A Category to continue</span>
  <% end %>
  <div class='add-group-btn'>
    <div class='group-btn shadow p-3 mb-5 rounded'>
      <%= link_to "Add Category", new_user_group_path(current_user), class: 'new-group-btn text-dark' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<nav class="container-fluid navbar navbar-expand-md bg-primary">
    <div class="container-fluid d-flex align-items-center justify-content-between">
    <div></div>
      <div class="nav-logo">        
        <h2><span class="bud">Add Category</span></h2>
      </div>
      <button class="navbar-toggler btn btn-outline-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item"> 
              <span class="nav-link me-5 text-light"><i class="fa fa-user me-2"></i><%= current_user.name %></span>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-sm btn-outline-warning mt-2' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_session_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<div class=" container d-flex flex-column justify-content-center align-items-center">
  <div class="budget-header w-100">
  <h1> <%= link_to user_groups_path do %>
    <i class="fa fa-arrow-left" aria-hidden="true" style="color: #3778c2; padding-left: 22px"> </i>
    <% end %>
    </h1>
  </div>
  <div class="card w-100 d-flex justify-content-center align-items-center  p-3 shadow p-3 mb-5 bg-body rounded">
    <h2 class=" d-flex p-2  mb-3"> Create New Category</h2>
     <%= form_with model: @group, url: user_groups_path(current_user),  scope: :group, class: 'd-flex flex-column  col-md-5 justify-content-center align-items-center' do |f| %>
      <div class="input-group p-2  mb-3">
        <%= f.label :icon, class: "input-group-text" %><br />
        <%= f.text_field :icon, autofocus: true, autocomplete: "icon", class: 'form-control' %>
      </div>

      <div class="input-group p-2 mb-3">
        <%= f.label :name, class: "input-group-text" %><br />
        <%= f.text_field :name, autocomplete: "name", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="d-flex flex-column justify-content-between min-vh-100 border bg-light">
  <div> 
    
  </div>
  <div class="d-flex flex-column justify-content-center ">
    <h1 class="finanz d-flex flex-column align-items-center">BUDGET</h1>  
  </div>
  <div class="text-center border-secondary">
    <div class="container mb-2">
      <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary w-100 fs-5" %>
    </div>
    <p>
    <%= link_to "SIGN UP", new_user_registration_path, class: "text-muted text-decoration-none" %>
    </p>    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>  
  <div class='container-fluid'>
    <% if notice %>
      <p class="alert alert-info position-absolute top-10 start-50 translate-middle" role="alert">
        <%= notice %>
        <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning mt-4 position-absolute top-10 start-50 translate-middle" role="alert">
        <%= alert %>
        <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </div>
      
    <script src="https://kit.fontawesome.com/b331332bf9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>